printWidth: 100
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
trailingComma: 'es5'
bracketSpacing: true
arrowParens: 'avoid'
endOfLine: 'auto'

overrides:
  - files: ['*.yml', '*.yaml', '.prettierrc']
    options:
      tabWidth: 2
  - files: ['schema/**/*']
    options:
      printWidth: 140
